### ISSUE TITLE
Host Unreachable error

### ISSUE THREAD

**Issue by morm075** [AMacro/dv-multiplayer#21] opened 2024-08-16 07:01 UTC
On third attempt, host unreachable is displayed.
https://discord.com/channels/332511223536943105/1234574186161377363/1272234980998647859

**Comment by AMacro** [comment] 2024-08-17 05:09
Issue caused by joining a server with a password, then joining a server without a password - resolved in release 0.1.8.0

**Closed by AMacro** 2024-08-17 05:09 UTC
